name: Test Github Action
on:
  push:
    branches: [ main, master ]
jobs:
  build and deploy spring-api
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
    - uses: actions/checkout@v4

    - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

    - name: Clean & Build with Maven
        run: mvn clean -B package --file pom.xml

    - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test-github-action:latest

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test-github-action:latest